### ISSUE TITLE
Fix "A component is changing an uncontrolled input to be controlled" bug on Donate page

### ISSUE THREAD

**Issue by SovereignAndrey** [AngelProtocolFinance/angelprotocol-web-app#1984]
Repro steps:
1. connect wallet
2. go to http://localhost:4200/donate/1
3. insert `0.1` as donation value
4. click "Submit"
5. check "I have read and I agree with Terms & Conditions." 
6. error appears:
```console
Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at div
    at Controller (http://localhost:4200/static/js/vendors-node_modules_cosmjs_cosmwasm-stargate_build_index_js-node_modules_hookform_error-mess-f85117.chunk.js:302087:35)
    at CheckField (http://localhost:4200/static/js/src_components_form_CheckField_tsx-src_components_form_Field_tsx.chunk.js:32:5)
    at form
    at Form (http://localhost:4200/static/js/src_components_KYC_index_tsx.chunk.js:345:5)
    at FormProvider (http://localhost:4200/static/js/vendors-node_modules_cosmjs_cosmwasm-stargate_build_index_js-node_modules_hookform_error-mess-f85117.chunk.js:301692:5)
    at KYC (http://localhost:4200/static/js/src_components_KYC_index_tsx.chunk.js:799:30)
    at CurrentStep (http://localhost:4200/static/js/src_components_donation_Steps_index_tsx.chunk.js:46:75)
    at div
    at Steps (http://localhost:4200/static/js/src_components_donation_Steps_index_tsx.chunk.js:2209:5)
    at div
    at Content (http://localhost:4200/static/js/src_pages_Donate_index_tsx.chunk.js:133:78)
    at QueryLoader (http://localhost:4200/static/js/src_App_App_tsx.chunk.js:3515:5)
    at section
    at Donate (http://localhost:4200/static/js/src_pages_Donate_index_tsx.chunk.js:276:66)
    at Outlet (http://localhost:4200/static/js/bundle.js:620529:26)
    at Suspense
    at div
    at Layout
    at Routes (http://localhost:4200/static/js/bundle.js:620621:5)
    at ModalContext (http://localhost:4200/static/js/bundle.js:1869:76)
    at WalletContext (http://localhost:4200/static/js/src_App_App_tsx.chunk.js:6551:71)
    at WalletProvider (http://localhost:4200/static/js/vendors-node_modules_cosmjs_cosmwasm-stargate_build_index_js-node_modules_hookform_error-mess-f85117.chunk.js:188250:5)
    at App (http://localhost:4200/static/js/src_App_App_tsx.chunk.js:66:81)
    at Suspense
    at Router (http://localhost:4200/static/js/bundle.js:620554:15)
    at BrowserRouter (http://localhost:4200/static/js/bundle.js:619363:5)
    at Provider (http://localhost:4200/static/js/bundle.js:616934:5)
    at ErrorHandler (http://localhost:4200/static/js/bundle.js:2383:77)
    at ErrorContext (http://localhost:4200/static/js/bundle.js:1597:69)
    at ModalContext (http://localhost:4200/static/js/bundle.js:1869:76)
    at ErrorBoundary (http://localhost:4200/static/js/bundle.js:2279:5)
```

**Comment by abbasali1994** [comment]
@SovereignAndrey cant replicate the error on local or on production url , is this error on RC-v1.8?

**Comment by SovereignAndrey** [comment]
@abbasali1994 Were to able to reproduce this on RC-v1.8?
